remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Calculador de Disipadores
logo: /assets/img/logo.png
description: Interfaz gráfica para el calculo de disipadores.
show_downloads: true
theme: jekyll-theme-midnight